version: '3.3'

services:
  mera_web:
    container_name: 'django-app-container'
    build: .
    ports:
      - "8001:8001"
          
  mera_db:
    container_name: 'mysql_container'
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'test@123'
